"use client";

import { cn } from "@/lib/utils";

const ACCENT_BG: Record<string, string> = {
  peach: "bg-peach-soft",
  lavender: "bg-lavender-soft",
  sage: "bg-sage-soft",
  rose: "bg-rose-soft",
  sun: "bg-sun-soft",
};

const ACCENT_BORDER: Record<string, string> = {
  peach: "border-peach-deep",
  lavender: "border-lavender-deep",
  sage: "border-sage-deep",
  rose: "border-rose-deep",
  sun: "border-sun-deep",
};

const ACCENT_HEX: Record<string, string> = {
  peach: "ffd6cc",
  lavender: "e3daff",
  sage: "d7ebd8",
  rose: "ffd1e0",
  sun: "ffeab3",
};

/**
 * Pixel-art avatar generated by DiceBear (pixel-art-neutral style).
 * Background fills with the user's accent color so each partner has
 * a recognizable badge in the UI.
 */
export function Avatar({
  seed,
  size = 32,
  accent = "peach",
  className,
}: {
  seed: string;
  size?: number;
  accent?: string;
  className?: string;
}) {
  const bg = ACCENT_HEX[accent] ?? ACCENT_HEX.peach;
  const url =
    `https://api.dicebear.com/9.x/pixel-art-neutral/svg?` +
    new URLSearchParams({
      seed,
      size: String(size * 2),
      backgroundColor: bg,
      radius: "50",
    }).toString();

  return (
    <span
      className={cn(
        "inline-flex shrink-0 items-center justify-center overflow-hidden rounded-full border-2",
        ACCENT_BG[accent] ?? "bg-peach-soft",
        ACCENT_BORDER[accent] ?? "border-peach-deep",
        className,
      )}
      style={{ width: size, height: size }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={url}
        alt=""
        width={size}
        height={size}
        className="w-full h-full object-cover"
        style={{ imageRendering: "pixelated" }}
      />
    </span>
  );
}
